version: "3.4"
services:
  web:
    build: .docker/nginx
    privileged: true
    command: nginx -g "daemon off;"
    ports:
      - 5001:80
    volumes:
      - .:/var/www/html

  php:
    build: .docker/php
    privileged: true
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - web

  db:
    image: mysql:8
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  # redis:
  #   image: redis:3.2-alpine
  #   ports:
  #     - 6381:6379
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g
